[workspace]
members = ["palette"]

[package]
name = "gouache"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
clap = {version = "4.3.2", features = ["derive"]}
env_logger = "0.10.0"
image = "0.24.6"
log = "0.4.18"
palette.path = "./palette"
